### ISSUE TITLE
Implement Tests

### ISSUE THREAD

**Issue by esron** [esron/systranca-server#19]
The controllers are getting bigger, that are already a lot of routes. It's time to invest in some TDD. 

I like Jest, but everybody is free to suggest the test framework they like the most.

**Comment by viniciusarre** [comment]
Hey @esron 
Are you looking for unit tests for now? Can I work on this?

**Comment by esron** [comment]
@viniciusarre , yes, for sure. 

You can gradually add tests to the routes that are already implemented, so we can establish a standard.

**Comment by viniciusarre** [comment]
I will work on this and create a WIP pull requests for reviews and possible improvements!

**Comment by esron** [comment]
This is done.
