### ISSUE TITLE
Token issuing logic

### ISSUE THREAD

**Issue by esron** [esron/systranca-server#6]
Implement the jwt token issuing logic.

Associate a token with a user.

**Comment by jhidalgoesp** [comment]
@esron, Hello I created a MR addressing this issue (#11 ).

**Comment by esron** [comment]
Solved in PR #11

**Comment by esron** [comment]
This issue needs to be reopened. The [Systranca App Issuing Logic Flow](https://github.com/esron/systranca_app/issues/8) is going to be implemented alongside with this one.

**Comment by meetKazuki** [comment]
Hi there @esron. I will like to jump on this

**Comment by esron** [comment]
Hi @meetKazuki , I was waiting for @theArtechnology to continue the discussion started in [this](https://github.com/esron/systranca_app/issues/8) thread.

**Comment by theArtechnology** [comment]
I've been busy recently, but I would be happy if we could discuss on that topic. First is that,
We need to do protected routes,

```
var unless = function(middleware, ...paths) {
  return function(req, res, next) {
    const pathCheck = paths.some(path => path === req.path);
    pathCheck ? next() : middleware(req, res, next);
  };
};

app.use(unless(validateToken, "/user/login", "/user/register, blabla/blabla"));
```

you can find validateToken [here](https://github.com/esron/systranca-server/blob/bc3a3b980701c93946ec1cc826e50996ae057666/controllers/AuthController.js#L65).

where the second parameter of unless is to exclude path that doesn't need JWT token.
Hope it helps !

**Comment by theArtechnology** [comment]
> Hi there @esron. I will like to jump on this. Can you please provide more context for this. Because from what I'm seeing, you've implemented the logic already with `AuthController.validateToken`

Yes, it is already here, but it was about the mobile application, you need to have protected routes on some of the paths. Practically all the paths were open. Having limited time, I suggest we open a discussion here, and find a consensus on the best practice. My proposition is up here. So some routes can be protected + routes that shouldn't be protect is excluded.

To link it to the mobile app, it was a bit useless to make a token logic where the routes itself didn't had JWT auth.

**Comment by esron** [comment]
I'll close this for now. The authentication flow is far from good but it is at least functional.
